spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
spring.datasource.username=postgres
spring.datasource.password=Pin@801698
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

ollama.base-url=http://localhost:11434
ollama.embed-model=nomic-embed-text
ollama.llm-model=qwen2.5-coder:1.5b

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
